export const PKG_PREFIX = '@m-eleplus-crud'
export const PKG_NAME = 'm-eleplus-crud'
export const PKG_CAMELCASE_NAME = 'MElePlusCrud'
export const PKG_CAMELCASE_LOCAL_NAME = 'MElePlusCrudLocale'
export const PKG_BRAND_NAME = 'M ElePlus Crud'
